# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\amol\PycharmProjects\mayatools\ui\playblastUI.ui'
#
# Created: Tue Apr 25 15:59:01 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(475, 473)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.HUD_3_LE = QtGui.QLineEdit(self.centralwidget)
        self.HUD_3_LE.setObjectName("HUD_3_LE")
        self.gridLayout_2.addWidget(self.HUD_3_LE, 0, 2, 1, 1)
        self.HUD_2_LE = QtGui.QLineEdit(self.centralwidget)
        self.HUD_2_LE.setObjectName("HUD_2_LE")
        self.gridLayout_2.addWidget(self.HUD_2_LE, 0, 1, 1, 1)
        self.HUD_1_LE = QtGui.QLineEdit(self.centralwidget)
        self.HUD_1_LE.setToolTip("")
        self.HUD_1_LE.setObjectName("HUD_1_LE")
        self.gridLayout_2.addWidget(self.HUD_1_LE, 0, 0, 1, 1)
        self.HUD_4_LE = QtGui.QLineEdit(self.centralwidget)
        self.HUD_4_LE.setObjectName("HUD_4_LE")
        self.gridLayout_2.addWidget(self.HUD_4_LE, 1, 0, 1, 1)
        self.HUD_5_LE = QtGui.QLineEdit(self.centralwidget)
        self.HUD_5_LE.setObjectName("HUD_5_LE")
        self.gridLayout_2.addWidget(self.HUD_5_LE, 1, 1, 1, 1)
        self.HUD_6_LE = QtGui.QLineEdit(self.centralwidget)
        self.HUD_6_LE.setObjectName("HUD_6_LE")
        self.gridLayout_2.addWidget(self.HUD_6_LE, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.camera_LW = QtGui.QListWidget(self.centralwidget)
        self.camera_LW.setObjectName("camera_LW")
        self.verticalLayout_2.addWidget(self.camera_LW)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.resolution_LW = QtGui.QListWidget(self.centralwidget)
        self.resolution_LW.setObjectName("resolution_LW")
        self.verticalLayout.addWidget(self.resolution_LW)
        self.custom_res_CB = QtGui.QCheckBox(self.centralwidget)
        self.custom_res_CB.setObjectName("custom_res_CB")
        self.verticalLayout.addWidget(self.custom_res_CB)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.custResX_SB = QtGui.QSpinBox(self.centralwidget)
        self.custResX_SB.setEnabled(False)
        self.custResX_SB.setAlignment(QtCore.Qt.AlignCenter)
        self.custResX_SB.setReadOnly(False)
        self.custResX_SB.setMinimum(0)
        self.custResX_SB.setMaximum(999999999)
        self.custResX_SB.setProperty("value", 1280)
        self.custResX_SB.setObjectName("custResX_SB")
        self.horizontalLayout.addWidget(self.custResX_SB)
        self.custResY_SB = QtGui.QSpinBox(self.centralwidget)
        self.custResY_SB.setEnabled(False)
        self.custResY_SB.setAlignment(QtCore.Qt.AlignCenter)
        self.custResY_SB.setMaximum(999999999)
        self.custResY_SB.setProperty("value", 720)
        self.custResY_SB.setObjectName("custResY_SB")
        self.horizontalLayout.addWidget(self.custResY_SB)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.startFrame_DSB = QtGui.QDoubleSpinBox(self.centralwidget)
        self.startFrame_DSB.setAlignment(QtCore.Qt.AlignCenter)
        self.startFrame_DSB.setMinimum(-999999999.0)
        self.startFrame_DSB.setMaximum(999999999.0)
        self.startFrame_DSB.setProperty("value", 0.0)
        self.startFrame_DSB.setObjectName("startFrame_DSB")
        self.gridLayout.addWidget(self.startFrame_DSB, 1, 0, 1, 1)
        self.endFrame_DSB = QtGui.QDoubleSpinBox(self.centralwidget)
        self.endFrame_DSB.setAlignment(QtCore.Qt.AlignCenter)
        self.endFrame_DSB.setMinimum(-999999999.0)
        self.endFrame_DSB.setMaximum(999999999.0)
        self.endFrame_DSB.setObjectName("endFrame_DSB")
        self.gridLayout.addWidget(self.endFrame_DSB, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.HUD_8_LE = QtGui.QLineEdit(self.centralwidget)
        self.HUD_8_LE.setObjectName("HUD_8_LE")
        self.gridLayout_3.addWidget(self.HUD_8_LE, 0, 1, 1, 1)
        self.HUD_10_LE = QtGui.QLineEdit(self.centralwidget)
        self.HUD_10_LE.setObjectName("HUD_10_LE")
        self.gridLayout_3.addWidget(self.HUD_10_LE, 1, 0, 1, 1)
        self.HUD_7_LE = QtGui.QLineEdit(self.centralwidget)
        self.HUD_7_LE.setObjectName("HUD_7_LE")
        self.gridLayout_3.addWidget(self.HUD_7_LE, 0, 0, 1, 1)
        self.HUD_9_LE = QtGui.QLineEdit(self.centralwidget)
        self.HUD_9_LE.setObjectName("HUD_9_LE")
        self.gridLayout_3.addWidget(self.HUD_9_LE, 0, 2, 1, 1)
        self.HUD_11_LE = QtGui.QLineEdit(self.centralwidget)
        self.HUD_11_LE.setObjectName("HUD_11_LE")
        self.gridLayout_3.addWidget(self.HUD_11_LE, 1, 1, 1, 1)
        self.HUD_12_LE = QtGui.QLineEdit(self.centralwidget)
        self.HUD_12_LE.setObjectName("HUD_12_LE")
        self.gridLayout_3.addWidget(self.HUD_12_LE, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.create_BTN = QtGui.QPushButton(self.centralwidget)
        self.create_BTN.setObjectName("create_BTN")
        self.horizontalLayout_3.addWidget(self.create_BTN)
        self.cancel_BTN = QtGui.QPushButton(self.centralwidget)
        self.cancel_BTN.setObjectName("cancel_BTN")
        self.horizontalLayout_3.addWidget(self.cancel_BTN)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.playblast_PB = QtGui.QProgressBar(self.centralwidget)
        self.playblast_PB.setProperty("value", 24)
        self.playblast_PB.setObjectName("playblast_PB")
        self.gridLayout_4.addWidget(self.playblast_PB, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 475, 21))
        self.menubar.setObjectName("menubar")
        self.menuPreference = QtGui.QMenu(self.menubar)
        self.menuPreference.setObjectName("menuPreference")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStyle = QtGui.QAction(MainWindow)
        self.actionStyle.setObjectName("actionStyle")
        self.actionFont = QtGui.QAction(MainWindow)
        self.actionFont.setObjectName("actionFont")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menuPreference.addAction(self.actionStyle)
        self.menuPreference.addAction(self.actionFont)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPreference.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_3_LE.setStatusTip(QtGui.QApplication.translate("MainWindow", "add heads up display 3", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_3_LE.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "heads up display 3", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_2_LE.setStatusTip(QtGui.QApplication.translate("MainWindow", "add heads up display 2", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_2_LE.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "heads up display 2", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_1_LE.setStatusTip(QtGui.QApplication.translate("MainWindow", "add heads up display 1", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_1_LE.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "heads up display 1", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_4_LE.setStatusTip(QtGui.QApplication.translate("MainWindow", "add heads up display 4", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_4_LE.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "heads up display 4", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_5_LE.setStatusTip(QtGui.QApplication.translate("MainWindow", "add heads up display 5", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_5_LE.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "heads up display 5", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_6_LE.setStatusTip(QtGui.QApplication.translate("MainWindow", "add heads up display 6", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_6_LE.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "heads up display 6", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Cameras", None, QtGui.QApplication.UnicodeUTF8))
        self.camera_LW.setStatusTip(QtGui.QApplication.translate("MainWindow", "All Camera\'s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Resolutions", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_LW.setStatusTip(QtGui.QApplication.translate("MainWindow", "All Resolutions", None, QtGui.QApplication.UnicodeUTF8))
        self.custom_res_CB.setText(QtGui.QApplication.translate("MainWindow", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.custResX_SB.setStatusTip(QtGui.QApplication.translate("MainWindow", "Custom Resolution X", None, QtGui.QApplication.UnicodeUTF8))
        self.custResY_SB.setStatusTip(QtGui.QApplication.translate("MainWindow", "Custom Resolution Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Start Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "EndFrame", None, QtGui.QApplication.UnicodeUTF8))
        self.startFrame_DSB.setStatusTip(QtGui.QApplication.translate("MainWindow", "Start Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.endFrame_DSB.setStatusTip(QtGui.QApplication.translate("MainWindow", "End Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_8_LE.setStatusTip(QtGui.QApplication.translate("MainWindow", "add heads up display 8", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_8_LE.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "heads up display 8", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_10_LE.setStatusTip(QtGui.QApplication.translate("MainWindow", "add heads up display 10", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_10_LE.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "heads up display 10", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_7_LE.setStatusTip(QtGui.QApplication.translate("MainWindow", "add heads up display 7", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_7_LE.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "heads up display 7", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_9_LE.setStatusTip(QtGui.QApplication.translate("MainWindow", "add heads up display 9", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_9_LE.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "heads up display 9", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_11_LE.setStatusTip(QtGui.QApplication.translate("MainWindow", "add heads up display 11", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_11_LE.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "heads up display 11", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_12_LE.setStatusTip(QtGui.QApplication.translate("MainWindow", "add heads up display 12", None, QtGui.QApplication.UnicodeUTF8))
        self.HUD_12_LE.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "heads up display 12", None, QtGui.QApplication.UnicodeUTF8))
        self.create_BTN.setStatusTip(QtGui.QApplication.translate("MainWindow", "Create Playblast", None, QtGui.QApplication.UnicodeUTF8))
        self.create_BTN.setText(QtGui.QApplication.translate("MainWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_BTN.setStatusTip(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_BTN.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPreference.setTitle(QtGui.QApplication.translate("MainWindow", "Preference", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStyle.setText(QtGui.QApplication.translate("MainWindow", "Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFont.setText(QtGui.QApplication.translate("MainWindow", "Font", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))

